"""empty message

Revision ID: 5c7d09e9e213
Revises: 4feb2a66a1b3
Create Date: 2025-04-29 00:36:46.739747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7d09e9e213'
down_revision = '4feb2a66a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_name_key', type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('gravity')
        batch_op.drop_column('gender')
        batch_op.drop_column('height')
        batch_op.drop_column('climate')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('favorites_name_key', ['name'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
